force-app/main/default/objects/SAID_Analysis__c/SAID_Analysis__c.object-meta.xml
<CustomObject>
    <label>SAID Analysis</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>SAID Analysis Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SAID Analysis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAID_Analysis__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAID_Analysis__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Men</fullName>
                <default>true</default>
                <label>Men</label>
            </value>
            <value>
                <fullName>Women</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAID_Analysis__c/fields/Permanent_Resident__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Resident__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permanent Resident</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAID_Analysis__c/fields/SA_Citizen__c.field-meta.xml
<CustomField>
    <fullName>SA_Citizen__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SA Citizen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SAID_Analysis__c/fields/SAID__c.field-meta.xml
<CustomField>
    <fullName>SAID__c</fullName>
    <label>SAID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SAID_Analysis__c/fields/Search_Count__c.field-meta.xml
<CustomField>
    <fullName>Search_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Search Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CloudsmithsController.cls
/**
 * @description       :
 * @author            : Roshan
 * @group             :
 * @last modified on  : 07-17-2023
 * @last modified by  : Roshan
 * Modifications Log
 * Ver   Date         Author    Modification
 * 1.0   07-10-2023   Roshan    Initial Version
 **/
public with sharing class CloudsmithsController {
    @AuraEnabled
    public static Object getAnalysisRecordBySaid(String said) {
        List<SAID_Analysis__c> analysis;
        System.debug(said);
        try {
            analysis = [
                SELECT Id, Birthdate__c, SAID__c, Gender__c, SA_Citizen__c, Permanent_Resident__c, Search_Count__c
                FROM SAID_Analysis__c
                WHERE SAID__c = :said
                WITH SECURITY_ENFORCED
            ];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return analysis.size() > 0 ? analysis[0] : null;
    }
}